defaults: 
  controllersPath: "./controllers/"
  host: "http://localhost:3000"
  imgPaths: "/images/:id/:size"
  readOnly: true

test:
  host: ""

production:
  host: "env:HOST"
  imgPaths: env:IMAGE_PATHS
  readOnly: env:READ_ONLY
